// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Node.js에서 .env 파일을 읽어 process.env에 주입해 주는 코드입니다.
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  // Prisma CLI가 사용할 스키마 파일의 경로입니다.
  schema: 'prisma/schema.prisma',
  // 마이그레이션 파일들이 저장될 경로를 지정합니다.
  // migrate dev 실행 시 생성되는 SQL/메타 파일들이 이 폴더에 쌓입니다.
  migrations: {
    path: 'prisma/migrations',
  },
  // Prisma CLI가 DB에 연결할 때 사용할 연결 문자열을 어디서 가져올지입니다.
  datasource: {
    url: env('DATABASE_URL'),
  },
});
